import { StyleSheet } from "react-native";
import C from "@/constants/colors";

export const styles = StyleSheet.create({
  header: {
    backgroundColor: C.surface,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    paddingHorizontal: 20,
    paddingBottom: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: {
    color: C.orange,
    fontSize: 17,
    fontFamily: "Inter_700Bold",
    letterSpacing: 0.5,
  },
  headerSub: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    marginTop: 1,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    margin: 16,
    marginBottom: 8,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    paddingHorizontal: 12,
  },
  searchInput: {
    flex: 1,
    color: C.text,
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    paddingVertical: 10,
  },
  scroll: {
    padding: 16,
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: 20,
    gap: 10,
  },
  emptyText: {
    color: C.dim,
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    textAlign: "center",
  },
  emptySubText: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
  },
  clientCard: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    padding: 14,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  clientLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: `${C.orange}22`,
    borderWidth: 1,
    borderColor: `${C.orange}44`,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    color: C.orange,
    fontSize: 13,
    fontFamily: "Inter_700Bold",
  },
  clientName: {
    color: C.text,
    fontSize: 15,
    fontFamily: "Inter_600SemiBold",
  },
  clientGoal: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    marginTop: 1,
  },
  clientMeta: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    marginTop: 2,
  },
  badge: {
    backgroundColor: C.orange,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 5,
  },
  badgeText: {
    color: C.white,
    fontSize: 12,
    fontFamily: "Inter_700Bold",
  },
  subHeader: {
    backgroundColor: C.surface,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  backBtn: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  clientDetailName: {
    color: C.text,
    fontSize: 16,
    fontFamily: "Inter_700Bold",
  },
  clientDetailGoal: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
  },
  viewTabs: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  viewTab: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: C.border,
  },
  viewTabActive: {
    borderColor: C.orange,
    backgroundColor: `${C.orange}15`,
  },
  viewTabText: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_500Medium",
  },
  viewTabTextActive: {
    color: C.orange,
  },
  prCard: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: "center",
    minWidth: 70,
  },
  prValue: {
    color: C.orange,
    fontSize: 18,
    fontFamily: "Inter_700Bold",
  },
  prLabel: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    marginTop: 2,
  },
  noteCard: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: `${C.orange}33`,
    borderRadius: 8,
    padding: 14,
    marginBottom: 14,
  },
  noteHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  noteLabel: {
    color: C.orange,
    fontSize: 13,
    fontFamily: "Inter_700Bold",
    letterSpacing: 0.5,
  },
  noteText: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    lineHeight: 20,
  },
  noteInput: {
    backgroundColor: C.surfaceAlt,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 6,
    padding: 10,
    color: C.text,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    minHeight: 80,
    textAlignVertical: "top",
    marginBottom: 8,
  },
  saveNoteBtn: {
    backgroundColor: C.orange,
    borderRadius: 6,
    padding: 10,
    alignItems: "center",
  },
  saveNoteBtnText: {
    color: C.white,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  chartCard: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    padding: 14,
    marginBottom: 14,
  },
  liftTab: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  liftTabActive: {
    borderColor: C.orange,
    backgroundColor: `${C.orange}15`,
  },
  liftTabText: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_500Medium",
  },
  liftTabTextActive: {
    color: C.orange,
  },
  sectionLabel: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_700Bold",
    letterSpacing: 2,
    marginBottom: 10,
  },
  dimText: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
  },
  entryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  entryLift: {
    color: C.orange,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  entryNote: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    marginTop: 2,
  },
  entryWeight: {
    color: C.text,
    fontSize: 14,
    fontFamily: "Inter_700Bold",
  },
  entrySetsReps: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
  },
  entryDate: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
  },
  fieldLabel: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    marginBottom: 8,
  },
  input: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    padding: 13,
    color: C.text,
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    marginBottom: 14,
  },
  row2: {
    flexDirection: "row",
  },
  errText: {
    color: C.red,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    marginBottom: 10,
  },
  logBtn: {
    backgroundColor: C.orange,
    borderRadius: 10,
    padding: 15,
    alignItems: "center",
    marginTop: 4,
  },
  logBtnText: {
    color: C.white,
    fontSize: 15,
    fontFamily: "Inter_700Bold",
  },
  successBanner: {
    backgroundColor: `${C.green}18`,
    borderWidth: 1,
    borderColor: `${C.green}44`,
    borderRadius: 8,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
  },
  successText: {
    color: C.green,
    fontSize: 13,
    fontFamily: "Inter_500Medium",
  },
  msgCard: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    padding: 14,
    marginBottom: 8,
  },
  msgTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  msgDate: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
  },
  msgText: {
    color: C.text,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    lineHeight: 20,
  },
  msgMeta: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    fontStyle: "italic",
    marginTop: 4,
  },
  replyBox: {
    backgroundColor: `${C.orange}0d`,
    borderLeftWidth: 2,
    borderLeftColor: C.orange,
    padding: 10,
    marginTop: 10,
    borderRadius: 4,
  },
  replyText: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    lineHeight: 18,
  },
  replyBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 8,
  },
  replyBtnText: {
    color: C.orange,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  assessCard: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    padding: 14,
    marginBottom: 8,
  },
  assessTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  pgExistingCard: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    padding: 14,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  pgExistingTitle: {
    color: C.text,
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    marginBottom: 2,
  },
  pgExistingMeta: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
  },
  pgExistingActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  pgDeliverBtn: {
    backgroundColor: C.green,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  },
  pgDeliverBtnText: {
    color: C.white,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  pgBuilder: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    padding: 16,
  },
  pgExRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  pgExNum: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: `${C.orange}22`,
    alignItems: "center",
    justifyContent: "center",
  },
  pgExNumText: {
    color: C.orange,
    fontSize: 13,
    fontFamily: "Inter_700Bold",
  },
  pgExRowName: {
    color: C.text,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  pgExRowDetail: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
  },
  pgExActions: {
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
  },
  pgAddExCard: {
    backgroundColor: `${C.orange}08`,
    borderWidth: 1,
    borderColor: `${C.orange}22`,
    borderRadius: 8,
    padding: 14,
  },
  pgAddExTitle: {
    color: C.orange,
    fontSize: 12,
    fontFamily: "Inter_700Bold",
    marginBottom: 10,
  },
  pgAddExBtn: {
    backgroundColor: C.orange,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 6,
  },
  pgAddExBtnText: {
    color: C.white,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  modal: {
    flex: 1,
    backgroundColor: C.bg,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    paddingTop: 20,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  modalTitle: {
    color: C.text,
    fontSize: 16,
    fontFamily: "Inter_700Bold",
  },
  modalBody: {
    padding: 16,
  },
  dashTabs: {
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    backgroundColor: C.bg,
    flexShrink: 0,
  },
  dashTabsContent: {
    flexDirection: "row",
    paddingHorizontal: 4,
  },
  dashTab: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 14,
    gap: 5,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  dashTabActive: {
    borderBottomColor: C.orange,
  },
  dashTabText: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  dashTabTextActive: {
    color: C.orange,
  },
  dashTabBadge: {
    backgroundColor: C.border,
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 1,
    minWidth: 18,
    alignItems: "center",
  },
  dashTabBadgeActive: {
    backgroundColor: `${C.orange}22`,
  },
  dashTabBadgeText: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_700Bold",
  },
  dashTabBadgeTextActive: {
    color: C.orange,
  },
  mailingHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  mailingCount: {
    color: C.text,
    fontSize: 15,
    fontFamily: "Inter_700Bold",
  },
  mailingNote: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    marginTop: 2,
  },
  quickMailBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: C.orange,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  quickMailText: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  emailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  emailAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: `${C.orange}22`,
    alignItems: "center",
    justifyContent: "center",
  },
  emailAvatarText: {
    color: C.orange,
    fontSize: 12,
    fontFamily: "Inter_700Bold",
  },
  emailName: {
    color: C.text,
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
  },
  emailAddr: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    marginTop: 1,
  },
  sourceTag: {
    backgroundColor: `${C.orange}14`,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  sourceTagSignup: {
    backgroundColor: `${C.green}14`,
  },
  sourceTagText: {
    color: C.orange,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  sourceTagTextSignup: {
    color: C.green,
  },
  signupGroupLabel: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_700Bold",
    letterSpacing: 0.8,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  signupCard: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    padding: 14,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  signupName: {
    color: C.text,
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
  },
  signupEmail: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    marginTop: 2,
  },
  signupMeta: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    marginTop: 1,
  },
  signupNote: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    fontStyle: "italic",
    marginTop: 4,
  },
  orderCard: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
  },
  orderHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 12,
  },
  orderName: {
    color: C.text,
    fontSize: 15,
    fontFamily: "Inter_700Bold",
    marginBottom: 2,
  },
  orderEmail: {
    color: C.orange,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    textDecorationLine: "underline",
  },
  orderStatusBadge: {
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  orderStatusText: {
    fontSize: 13,
    fontFamily: "Inter_700Bold",
  },
  orderDetails: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  orderDetailRow: {
    flexDirection: "row",
    gap: 4,
    alignItems: "center",
    backgroundColor: C.bg,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  orderDetailLabel: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  orderDetailValue: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
  },
  orderSection: {
    marginBottom: 10,
  },
  orderSectionLabel: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0.3,
    marginBottom: 4,
  },
  orderSectionText: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    lineHeight: 20,
  },
  orderActions: {
    flexDirection: "row",
    gap: 8,
    marginTop: 6,
    marginBottom: 8,
  },
  orderActionEmail: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    paddingVertical: 10,
  },
  orderActionEmailText: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  orderActionSent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: C.green,
  },
  orderActionSentText: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  orderDate: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
  },
  inqSectionLabel: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_700Bold",
    letterSpacing: 1.2,
    marginBottom: 8,
    marginTop: 4,
  },
  inqCard: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
  },
  inqHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 10,
  },
  inqName: {
    color: C.text,
    fontSize: 15,
    fontFamily: "Inter_700Bold",
    marginBottom: 2,
  },
  inqEmail: {
    color: C.orange,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
  },
  inqBadge: {
    borderWidth: 1,
    borderColor: `${C.orange}66`,
    backgroundColor: `${C.orange}18`,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  inqBadgeDone: {
    borderColor: `${C.green}66`,
    backgroundColor: `${C.green}18`,
  },
  inqBadgeText: {
    color: C.orange,
    fontSize: 12,
    fontFamily: "Inter_700Bold",
  },
  inqBadgeTextDone: {
    color: C.green,
  },
  inqTypeBadge: {
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.bg,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  inqTypeBadgeText: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  inqDetail: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 6,
  },
  inqDetailLabel: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    minWidth: 60,
  },
  inqDetailValue: {
    color: C.text,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    flex: 1,
  },
  inqNotes: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    lineHeight: 20,
    marginBottom: 10,
  },
  inqActions: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
  },
  inqActionEmail: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    paddingVertical: 10,
  },
  inqActionEmailText: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  inqActionDone: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: C.green,
  },
  inqActionDoneText: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  inqDate: {
    color: C.muted,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
  },
  coachCard: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 12,
    marginBottom: 10,
    overflow: "hidden",
  },
  coachHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    padding: 14,
  },
  coachHeaderLeft: {
    flex: 1,
    paddingRight: 8,
  },
  coachHeaderRight: {
    alignItems: "flex-end",
  },
  coachName: {
    color: C.text,
    fontSize: 15,
    fontFamily: "Inter_700Bold",
    marginBottom: 4,
  },
  coachMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  coachPlanBadge: {
    borderWidth: 1,
    borderColor: `${C.orange}44`,
    backgroundColor: `${C.orange}11`,
    borderRadius: 5,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  coachPlanText: {
    fontSize: 12,
    fontFamily: "Inter_700Bold",
    color: C.orange,
  },
  coachStatusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  coachStatusLabel: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
  },
  checkInDone: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  checkInMissing: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  checkInStatusText: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  coachDetail: {
    borderTopWidth: 1,
    borderTopColor: C.border,
    padding: 14,
    paddingTop: 12,
  },
  coachSectionLabel: {
    color: C.dim,
    fontSize: 11,
    fontFamily: "Inter_700Bold",
    letterSpacing: 1.2,
    marginBottom: 8,
  },
  coachCheckInCard: {
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  coachRatingRow: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  coachRatingItem: {
    alignItems: "center",
  },
  coachRatingLabel: {
    color: C.dim,
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  coachRatingVal: {
    color: C.text,
    fontSize: 18,
    fontFamily: "Inter_700Bold",
  },
  coachFieldRow: {
    marginBottom: 8,
  },
  coachFieldLabel: {
    color: C.dim,
    fontSize: 10,
    fontFamily: "Inter_700Bold",
    letterSpacing: 1.2,
    marginBottom: 3,
  },
  coachFieldValue: {
    color: C.text,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    lineHeight: 19,
  },
  coachReplyDone: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    marginTop: 8,
    backgroundColor: `${C.green}0f`,
    borderRadius: 6,
    padding: 8,
  },
  coachReplyDoneText: {
    color: C.green,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    flex: 1,
    lineHeight: 18,
  },
  coachReplyBox: {
    marginTop: 8,
    gap: 8,
  },
  coachReplyInput: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    padding: 10,
    color: C.text,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    minHeight: 72,
    textAlignVertical: "top",
  },
  coachReplyBtn: {
    backgroundColor: C.orange,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
  },
  coachReplyBtnText: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  coachNoCheckIn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: `#e8404012`,
    borderWidth: 1,
    borderColor: `#e8404033`,
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  coachNoCheckInText: {
    color: "#e84040",
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    flex: 1,
  },
  coachPrevCard: {
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 6,
    padding: 8,
    marginBottom: 6,
  },
  coachPrevTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  coachPrevWeek: {
    color: C.text,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  coachPrevRatings: {
    flexDirection: "row",
    gap: 8,
  },
  coachPrevRating: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  coachPrevQ: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    lineHeight: 17,
  },
  coachSubRow: {
    flexDirection: "row",
    gap: 6,
    marginBottom: 8,
  },
  coachSubPill: {
    flex: 1,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    padding: 8,
    alignItems: "center",
  },
  coachSubPillText: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_700Bold",
    marginBottom: 2,
  },
  coachSubPillPrice: {
    color: C.dim,
    fontSize: 11,
    fontFamily: "Inter_400Regular",
  },
  coachSubActions: {
    gap: 6,
    marginBottom: 8,
  },
  coachSubStatusBtn: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    padding: 10,
    alignItems: "center",
  },
  coachSubStatusText: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  coachSubRemoveBtn: {
    alignItems: "center",
    paddingVertical: 8,
  },
  coachSubRemoveText: {
    color: "#e84040",
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  coachEmailBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    paddingVertical: 10,
    marginTop: 4,
  },
  coachEmailBtnText: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  coachNoPlanCard: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  coachNoPlanName: {
    color: C.text,
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    marginBottom: 2,
  },
  coachNoPlanEmail: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
  },
  coachNoPlanActions: {
    flexDirection: "row",
    gap: 5,
  },
  coachNoPlanBtn: {
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  coachNoPlanBtnText: {
    fontSize: 12,
    fontFamily: "Inter_700Bold",
  },
  coachConfigureBtn: {
    backgroundColor: C.orange,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  coachConfigureBtnText: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  coachPkgCard: {
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    gap: 8,
  },
  coachPkgRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  coachPkgLabel: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    width: 80,
  },
  coachPkgVal: {
    color: C.text,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    flex: 1,
    textAlign: "right",
  },
  coachEditPkgBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderColor: `${C.orange}55`,
    backgroundColor: `${C.orange}11`,
    borderRadius: 7,
    paddingVertical: 8,
    justifyContent: "center",
    marginBottom: 10,
  },
  coachEditPkgText: {
    color: C.orange,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  pkgBuilderLabel: {
    color: C.dim,
    fontSize: 11,
    fontFamily: "Inter_700Bold",
    letterSpacing: 1.2,
    marginBottom: 6,
    marginTop: 6,
  },
  pkgBuilderInput: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    padding: 11,
    color: C.text,
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    marginBottom: 8,
  },
  pkgBuilderSectionTitle: {
    color: C.text,
    fontSize: 15,
    fontFamily: "Inter_600SemiBold",
    marginBottom: 2,
  },
  pkgBuilderSectionSub: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
  },
  pkgToggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  pkgToggle: {
    width: 46,
    height: 26,
    borderRadius: 13,
    backgroundColor: C.border,
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  pkgToggleOn: {
    backgroundColor: C.orange,
  },
  pkgToggleThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#fff",
  },
  pkgToggleThumbOn: {
    alignSelf: "flex-end",
  },
  pkgFreqRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    paddingTop: 10,
    paddingBottom: 4,
  },
  pkgFreqChip: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  pkgFreqChipActive: {
    backgroundColor: `${C.orange}22`,
    borderColor: `${C.orange}88`,
  },
  pkgFreqChipText: {
    color: C.dim,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  pkgFreqChipTextActive: {
    color: C.orange,
  },
  pkgSaveBtn: {
    backgroundColor: C.orange,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 24,
  },
  pkgSaveBtnText: {
    color: "#fff",
    fontSize: 15,
    fontFamily: "Inter_700Bold",
  },
  tmplGroupRow: {
    flexDirection: "row",
    gap: 6,
    marginBottom: 12,
  },
  tmplGroupTab: {
    flex: 1,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    paddingVertical: 7,
    alignItems: "center",
  },
  tmplGroupTabActive: {
    backgroundColor: `${C.orange}22`,
    borderColor: `${C.orange}66`,
  },
  tmplGroupText: {
    color: C.dim,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  tmplGroupTextActive: {
    color: C.orange,
  },
  tmplScroll: {
    marginHorizontal: -18,
  },
  tmplScrollContent: {
    paddingHorizontal: 18,
    gap: 8,
    paddingBottom: 4,
  },
  tmplCard: {
    width: 150,
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    padding: 12,
  },
  tmplCardActive: {
    borderColor: `${C.orange}77`,
    backgroundColor: `${C.orange}0d`,
  },
  tmplCardName: {
    color: C.text,
    fontSize: 12,
    fontFamily: "Inter_700Bold",
    marginBottom: 3,
    lineHeight: 16,
  },
  tmplCardTagline: {
    color: C.dim,
    fontSize: 11,
    fontFamily: "Inter_400Regular",
    marginBottom: 8,
    lineHeight: 15,
  },
  tmplCardDetails: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    marginBottom: 8,
  },
  tmplChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  tmplChipText: {
    color: C.dim,
    fontSize: 10,
    fontFamily: "Inter_600SemiBold",
  },
  tmplCardPrice: {
    color: C.text,
    fontSize: 14,
    fontFamily: "Inter_700Bold",
  },
});

